<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f29d78f5-96c1-45ec-8191-f08fe3b1903c</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.10" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
    <PackageReference Include="Serilog.Sinks.Seq" Version="9.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\Api\" />
    <Folder Include="Controllers\Mvc\" />
    <Folder Include="DTOs\Account\" />
    <Folder Include="DTOs\Admin\" />
    <Folder Include="DTOs\ComplaintBoard\" />
    <Folder Include="DTOs\ElectricityReadings\" />
    <Folder Include="DTOs\Residences\" />
    <Folder Include="DTOs\Utilities\" />
    <Folder Include="DTOs\UtilityProviders\" />
    <Folder Include="DTOs\WaterReadings\" />
    <Folder Include="Interface\Mapping\" />
    <Folder Include="Interface\Service\" />
    <Folder Include="Mapping\" />
    <Folder Include="Models\Authentication\" />
    <Folder Include="Models\ComplaintBoard\" />
    <Folder Include="Models\ElectricityReadings\" />
    <Folder Include="Models\Residences\" />
    <Folder Include="Models\Utilities\" />
    <Folder Include="Models\UtilityProviders\" />
    <Folder Include="Models\WaterReadings\" />
    <Folder Include="Services\" />
    <Folder Include="wwwroot\lib\dt\css\" />
  </ItemGroup>

</Project>
